### ISSUE TITLE
Cannot Run Code Using GPUs

### ISSUE THREAD

**Issue by keshra123** [Alescontrela/viper_rl#1]
#### Description
Currently, I am trying to run the code using GPUs instead of CPUs to speed up the process, but I am unable to make changes to the code to make it work.
#### Code Output
`python scripts/train_vqgan.py -o viper_rl_data/checkpoints/atari_vqgan -c viper_rl/configs/vqgan/atari.yaml
WARNING:absl:GlobalAsyncCheckpointManager is not imported correctly. Checkpointing of GlobalDeviceArrays will not be available.To use the feature, install tensorstore.
WARNING:jax._src.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
JAX process: 0 / 1
JAX total devices: 1
JAX local devices: 1
Logging to viper_rl_data/checkpoints/atari_vqgan
'
#### To Reproduce
I changed all mentions of CPU in code to GPU and made sure that CUDA was running. I also tried to change the packages installed to run CUDA specifically

**Comment by escontra** [comment]
Strange, the video model training code was trained on both GPU and TPU. Are you sure you installed the correct version of Jax that matches your CUDA version?

https://github.com/google/jax#pip-installation-gpu-cuda-installed-via-pip-easier

**Comment by keshra123** [comment]
I believe so. I checked using nvcc --version command and installed using the CUDA 11 pip command provided in the documentation.

**Comment by escontra** [comment]
Hm, this seems like an issue with your install / Jax not finding the right CUDA install path. I would try to set the following variables:

```
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/cuda/include:$LD_LIBRARY_PATH
```

**Comment by keshra123** [comment]
![Screenshot from 2023-06-12 13-48-49](https://github.com/Alescontrela/viper_rl/assets/57604594/145eb4ca-0edf-4e3b-8a93-6e886ace04ed)
Unfortunately, my result is still the same after setting the following variables. I am not sure why it is still doesn't detect any GPUs being used.

**Comment by keshra123** [comment]
I went back and try reinstalling the correct version of jax for cuda and it is currently running with no errors which is why I am closing this issue. Thank you so much for your help and I will make sure to reach out if I run into any more problems. 
![Screenshot from 2023-06-12 14-12-59](https://github.com/Alescontrela/viper_rl/assets/57604594/e412d25d-dc49-499b-a254-80a432155eff)

**Comment by NonsansWD** [comment]
> I went back and try reinstalling the correct version of jax for cuda and it is currently running with no errors which is why I am closing this issue. Thank you so much for your help and I will make sure to reach out if I run into any more problems. !

After i made it work it always states failed dnn library initialization and states "couldnt create cudnn handle" did you experience that at all?

**Comment by Benjamin-So** [comment]
@NonsansWD I'm having the same issue. Did you have any success resolving the issue?

**Comment by JJYSTEM** [comment]
> [@NonsansWD](https://github.com/NonsansWD) I'm having the same issue. Did you have any success resolving the issue?

Solve it by installing the corresponding cuda and cudnn version, to python, jax.
